name = "nakai"
version = "0.8.0"
licences = ["MIT"]
description = "HTML generation for Gleam, on the server or anywhere else"
repository = { type = "github", user = "nakaixo", repo = "nakai" }
links = [
  { title = "Website", href = "https://nakaixo.github.io" },
  { title = "Sponsor", href = "https://github.com/sponsors/aslilac" },
]

internal_modules = ["nakai/internal/*", "nakai/experimental/*"]
gleam = ">= 0.33.0"

[dependencies]
gleam_stdlib = "~> 0.34"

[dev-dependencies]
gleam_erlang = "~> 0.23"
gleam_json = "~> 0.7"
gleeunit = "~> 1.0"
glychee = "~> 0.3"
